INSERT INTO movie_genre(genre_name)
VALUES
('Action'),
('Animation'),
('Aventure'),
('Biographie'),
('Catastrophe'),
('Comédie'),
('Comédie Dramatique'),
('Comédie Musicale'),
('Comédie Policiére'),
('Comédie Romantique'),
('Court Métrage'),
('Dessin Animé'),
('Documentaire'),
('Drame'),
('Drame Psychologique'),
('Epouvante'),
('Erotique'),
('Espionnage'),
('Essai'),
('Fantastique'),
('Film Musical'),
('Grand Spectacle'),
('Guerre'),
('Historique'),
('Horreur'),
('Karaté'),
('Manga'),
('Mélodrame'),
('Muet'),
('Péplum'),
('Policier'),
('Politique'),
('Programme'),
('Romance'),
('Science Fiction'),
('Sérial'),
('Spectacle'),
('Téléfilm'),
('Théatre'),
('Thriller'),
('Western');

INSERT INTO `user_mymovies` (`user_id`, `user_username`, `user_role`, `user_password`) VALUES
(1, 'Admin1', 'ADMIN', 'ad53c49e613b1d6892279e55c9b54c2a'),
(2, 'Visiteur1', 'VISITOR', 'dcaa6e60155776107c638af755498759');

INSERT INTO `movie` (`mov_id`, `mov_name`, `mov_description_short`, `mov_description_long`, `mov_author`, `mov_year`, `mov_poster`, `mov_mark`, `mov_genre`) VALUES
(1, 'Avengers : L&#039;Ère d&#039;Ultron', 'Avengers : L&#039;Ère d&#039;Ultron (Avengers: Age of Ultron) est un film de super-héros américain écrit et réalisé par Joss Whedon, produit par Marvel Studios, distribué par Walt Disney Studios Distribution et sorti en 2015. Il est basé sur l&#039;équipe de super-héros tirée des comics Marvel, les Avengers.', 'Alors que Tony Stark tente de relancer un programme de maintien de la paix jusque-là suspendu, les choses tournent mal et les super-héros Iron Man, Captain America, Thor, Hulk, Black Widow et Hawkeye vont devoir à nouveau unir leurs forces pour combattre le plus puissant de leurs adversaires : le terrible Ultron, un être technologique terrifiant qui s’est juré d’éradiquer l’espèce humaine. Afin d’empêcher celui-ci d’accomplir ses sombres desseins, des alliances inattendues se scellent, les entraînant dans une incroyable aventure et une haletante course contre le temps…', 'Joss Whedon', 2015, 'images/Avengers___L__039___re_d__039_Ultron785.png', 0, 1),
(2, '2012', '2012 est un film catastrophe américain écrit et réalisé par Roland Emmerich, sorti en 2009. Il fait référence au mayanisme d&#039;Amérique centrale avec son calendrier à long terme et son scénario décrit les conséquences de la survenance d&#039;événements cataclysmiques du type de ceux qui étaient censés se produire en 2012.', 'Les Mayas, l&#039;une des plus fascinantes civilisations que la Terre ait portées, nous ont transmis une prophétie : leur calendrier prend fin en 2012, et notre monde aussi. Depuis, les astrologues l&#039;ont confirmé, les numérologues l&#039;ont prédit, les géophysiciens trouvent cela dangereusement plausible, et même les experts scientifiques gouvernementaux finissent par arriver à cette terrifiante conclusion. La prophétie maya a été examinée, discutée, minutieusement analysée. En 2012, nous saurons tous si elle est vraie, mais quelques-uns auront été prévenus depuis longtemps... Lorsque les plaques tectoniques se mettent à glisser, provoquant de multiples séismes et détruisant Los Angeles au passage, Jackson Curtis, romancier, et sa famille se jettent à corps perdu, comme des millions d&#039;individus, dans un voyage désespéré. Tous ne pourront pas être sauvés...', 'Roland Emmerich', 2009, 'images/2012670.png', 0, 5),
(3, 'Star Wars, épisode I - La Menace fantôme', 'Star Wars, épisode I : La Menace fantôme (Star Wars Episode I: The Phantom Menace) est un film américain de science-fiction de type space opera sorti en 1999 écrit et réalisé par George Lucas.', 'Il y a bien longtemps, dans une galaxie très lointaine... La République connaît de nombreux tourments : la corruption fait vaciller ses bases, le Sénat s&#039;embourbe dans des discussions politiques sans fin et de nombreux pouvoirs dissidents commencent à émerger, annonçant la chute d&#039;un système autrefois paisible. Puissante et intouchable, la Fédération du Commerce impose par la force la taxation des routes commerciales. Refusant de céder, la pacifique planète Naboo, dirigée par la jeune Reine Amidala, subit un blocus militaire de la Fédération. Dépêchés par le Sénat pour régler cette affaire, les chevaliers Jedi Qui-Gon Jinn et Obi-Wan Kenobi découvrent qu&#039;une véritable offensive de la Fédération est imminente. Libérant la Reine et ses proches, ils quittent la planète mais doivent se poser sur Tatooine pour réparer leur vaisseau...', 'George Lucas', 1999, 'images/Star_Wars____pisode_I_-_La_Menace_fant__me172.png', 0, 35),
(4, 'Toy Story 3', 'Toy Story 3, ou Histoire de jouets 3, au Québec, est un film d&#039;animation en images de synthèse américain. Il est le troisième film de la série des Toy Story. Il a été produit par Pixar, distribué par Walt Disney Pictures et réalisé par Lee Unkrich.', 'Les créateurs des très populaires films Toy Story ouvrent à nouveau le coffre à jouets et invitent les spectateurs à retrouver le monde délicieusement magique de Woody et Buzz au moment où Andy s&#039;apprête à partir pour l&#039;université. Délaissée, la plus célèbre bande de jouets se retrouve... à la crèche ! Les bambins déchaînés et leurs petits doigts capables de tout arracher sont une vraie menace pour nos amis ! Il devient urgent d&#039;échafauder un plan pour leur échapper au plus vite. Quelques nouveaux venus vont se joindre à la Grande évasion, dont l&#039;éternel séducteur et célibataire Ken, compagnon de Barbie, un hérisson comédien nommé Larosse, et un ours rose parfumé à la fraise appelé Lotso.', 'Lee Unkrich', 2010, 'images/Toy_Story_3104.png', 0, 2),
(5, 'Man of Steel', 'Man of Steel ou L&#039;Homme d&#039;acier au Québec est un film américain réalisé par Zack Snyder, écrit par David S. Goyer et produit par Christopher Nolan, sorti en 2013. Basé sur Superman, personnage de DC Comics, le long-métrage est un reboot qui dépeint les origines du super-héros.', 'Un petit garçon découvre qu&#039;il possède des pouvoirs surnaturels et qu&#039;il n&#039;est pas né sur Terre. Plus tard, il s&#039;engage dans un périple afin de comprendre d&#039;où il vient et pourquoi il a été envoyé sur notre planète. Mais il devra devenir un héros s&#039;il veut sauver le monde de la destruction totale et incarner l&#039;espoir pour toute l&#039;humanité.', 'Zack Snyder', 2013, 'images/Man_of_Steel619.png', 0, 1),
(6, 'Ronaldo', 'Ronaldo est un film biographique documentaire britannique réalisé par Anthony Wonke en 2015. Il s&#039;agit d&#039;un film centré sur la vie du joueur de football portugais Cristiano Ronaldo, qui joue encore au moment de la sortie du film.', 'Tourné sur 14 mois avec un accès sans précédent dans le cercle proche de l&#039;homme et le sport. C&#039;est un film sur l&#039;une des figures les plus célèbres de l&#039;histoire du football. Pour la première fois, dans l&#039;intimité du joueur: père, famille, homme et ami dans ce documentaire fascinant. Grâce à des conversations en profondeur, des images de football et des images d&#039;archives inédites, le film donne un aperçu étonnant dans ce sport et la vie personnelle du triple Ballon d&#039;Or Cristiano Ronaldo à l&#039;apogée de sa carrière.', 'Anthony Wonke', 2015, 'images/Ronaldo123.png', 0, 4),
(7, '007 Spectre', '007 Spectre est un film d&#039;espionnage américano-britannique réalisé par Sam Mendes, sorti en 2015.', 'Un message cryptique venu tout droit de son passé pousse Bond à enquêter sur une sinistre organisation. Alors que M affronte une tempête politique pour que les services secrets puissent continuer à opérer, Bond s&#039;échine à révéler la terrible vérité derrière... le Spectre.', 'Sam Mendes', 2015, 'images/007_Spectre916.png', 0, 18);
