INSERT INTO movie_genre(genre_name)
VALUES
('Action'),
('Animation'),
('Aventure'),
('Biographique'),
('Catastrophe'),
('Comédie'),
('Comédie Dramatique'),
('Comédie Musicale'),
('Comédie Policiére'),
('Comédie Romantique'),
('Court Métrage'),
('Dessin Animé'),
('Documentaire'),
('Drame'),
('Drame Psychologique'),
('Epouvante'),
('Erotique'),
('Espionnage'),
('Essai'),
('Fantastique'),
('Film Musical'),
('Grand Spectacle'),
('Guerre'),
('Historique'),
('Horreur'),
('Karaté'),
('Manga'),
('Mélodrame'),
('Muet'),
('Péplum'),
('Policier'),
('Politique'),
('Programme'),
('Romance'),
('Science Fiction'),
('Sérial'),
('Spectacle'),
('Téléfilm'),
('Théatre'),
('Thriller'),
('Western');

INSERT INTO `mymovies`.`user_mymovies` (`user_id`, `user_username`, `user_role`, `user_password`) VALUES (NULL, 'Admin1', 'ADMIN', '9e6d5f635e1ca9bc7434772cef0c9a25');
